kubescape/storage

pkg/apiserver/apiserver.go, pkg/apiserver/serializer.go, pkg/apiserver/serializer_test.go
Prior to this PR, the types that this APIServer declared did not support Protobuf, yet the default APIServer configuration advertised it as supported. This led to certain requests made in Protobuf format fail and could lead to error messages in the server logs and unexpected issues in the cluster. One of the issues we have found is not being able to delete namespaces when the APIServer was running (see https://github.com/kubernetes/kubernetes/issues/86666).
This PR introduces a default serializer that rejects the Protobuf content type, thus not advertizing support for it, making clients fall back to other supported content types.
=> fix: reject Protobuf requests

pkg/registry/file/vulnarabilitysummarystoarge_test.go
Bug fix
___
This PR addresses an issue in the unit test 'TestVulnSummaryStorageImpl_GetList' where the returned order in the list was not always the same, causing the test to fail intermittently. The fix involves changing the assertion to check for deep equality of list items regardless of their order.
___
`pkg/registry/file/vulnarabilitysummarystoarge_test.go`: Modified the assertion in 'TestVulnSummaryStorageImpl_GetList' test to check for deep equality of list items regardless of their order. This is done by iterating over the items and checking if each item exists in the expected list, instead of directly comparing the two lists.
___
=> The returned order in the list is not always the same

pkg/registry/file/storage.go, pkg/registry/file/storage_test.go, pkg/registry/file/vulnerabilitysummarystorage_test.go
Bug fix
___
This pull request introduces an 'AlreadyExists' error handling in the generic storage implementation. It adds a new function 'Exists' to check if an object with a given key already exists in the storage. If an attempt is made to create an object that already exists, a 'KeyExistsError' is returned. The changes are covered with corresponding unit tests.
___
<details> <summary>files:</summary>
`pkg/registry/file/storage.go`: Added a new function 'Exists' to check if an object with a given key already exists in the storage. Modified the 'Create' function to return a 'KeyExistsError' if an attempt is made to create an object that already exists.
`pkg/registry/file/storage_test.go`: Added a new test 'TestStorageImpl_Exists' to verify the functionality of the 'Exists' function and …
=> fix: return already exists error

main.go
Instead of loading the account from a config map, we will load it from an env var, since account has been moved to a secret.
Not applying the same approach as other components since when importing the `github.com/kubescape/backend` package we have dependencies issues
=> Load account from env var

pkg/registry/file/storage.go, pkg/registry/file/storage_test.go, pkg/registry/file/vulnerabilitysummarystorage_test.go
Commit b528275d4e819e61fdd57448598b5e2141bbc84e introduced a bug which prevented resources from updating and failed the [system tests](https://github.com/kubescape/storage/actions/runs/6641795154/job/18070792161).
This PR reverts the commit. It keeps the filesystem limit fix functioning.
=> Revert "fix: return already exists error"

pkg/apis/softwarecomposition/types.go, pkg/apis/softwarecomposition/v1beta1/types.go, pkg/apis/softwarecomposition/v1beta1/zz_generated.conversion.go, pkg/apis/softwarecomposition/v1beta1/zz_generated.deepcopy.go, pkg/apis/softwarecomposition/zz_generated.deepcopy.go, pkg/generated/openapi/zz_generated.openapi.go
Enhancement
___
This PR introduces the following changes:
- Adds a new field 'Syscalls' to the ApplicationProfileContainer struct in both 'types.go' and 'v1beta1/types.go' files.
- Updates the conversion functions in 'zz_generated.conversion.go' to include the new 'Syscalls' field.
- Updates the deepcopy functions in 'zz_generated.deepcopy.go' to handle the new 'Syscalls' field.
- Updates the schema in 'zz_generated.openapi.go' to reflect the new 'Syscalls' field.
___
<details> <summary>files:</summary>
`pkg/apis/softwarecomposition/types.go`: Added 'Syscalls' field to the ApplicationProfileContainer struct.
`pkg/apis/softwarecomposition/v1beta1/types.go`: Added 'Syscalls' field to the ApplicationProfileContainer struct with json annotations. …
=> add syscalls

pkg/registry/file/generatednetworkpolicy.go, pkg/registry/file/storage.go
Enhancement
___
This PR enhances the functionality of the application by implementing the retrieval of known servers from storage. The changes include:
- Addition of a new constant `knownServersResource` in the `generatednetworkpolicy.go` file.
- Modification of the `Get` and `GetList` methods in the `generatednetworkpolicy.go` file to fetch known servers from the real store and use them in generating network policies.
- Addition of a new method `GetClusterScopedResource` in the `storage.go` file to fetch all objects in a given cluster, given their API version and kind.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Add known servers

README.md, hack/update-codegen.sh
Documentation
___
This Pull Request aims to enhance the documentation on how to work with the Storage Aggregated APIServer. The main changes include:
- Instructions on how to generate code and build in the main README.
- Guidelines on how to run in local k8s for development.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> docs: How to work with Storage

pkg/apis/softwarecomposition/networkpolicy/networkpolicy.go, pkg/apis/softwarecomposition/networkpolicy/networkpolicy_test.go
bug_fix, tests
___
This PR addresses the issue of IP duplication in the network policy. The main changes include:
- Implementing a hashing function to create unique identifiers for each rule and policy reference.
- Using these hashes to prevent duplication in both ingress and egress rules.
- Adding a new test case to verify the correct functioning of the IP duplication fix.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Fixed IP duplication

main.go, pkg/cleanup/cleanup.go, pkg/cleanup/discovery.go
bug_fix, enhancement
___
- The cleanup interval for resources is now configurable through an environment variable. If the environment variable is not set or cannot be parsed, a default value of 24 hours is used.
- The cleanup handler's logging has been improved to include the cleanup interval when a cleanup task starts and to log deletions at the debug level.
- The metadata loading function has been updated to also load labels from the metadata file.
- The function to delete resources by template hash or wlid has been updated to look for the template hash in the labels instead of the annotations.
- The list of workloads to cleanup has been reduced to only include cronjob, daemonset, deployment, job, pod, replicaset, and statefulset.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; …
=> fix cleanup of resources

pkg/apis/softwarecomposition/v1beta1/network_types.go, pkg/apis/softwarecomposition/v1beta1/networkpolicy/networkpolicy.go, pkg/apis/softwarecomposition/v1beta1/networkpolicy/networkpolicy_test.go, pkg/apis/softwarecomposition/v1beta1/types.go, pkg/registry/file/generatednetworkpolicy.go, pkg/registry/file/generatednetworkpolicy_test.go
enhancement, tests
___
This PR focuses on moving the Network Policy generation to the `v1beta1` version. The main changes include:
- Making certain fields optional in various structs by adding `omitempty` to their JSON tags. These fields include `PoliciesRef` in `GeneratedNetworkPolicy`, `Relevant` in `VulnerabilityCounters`, and `WorkloadVulnerabilitiesObj` in `VulnerabilitiesComponents`.
- Updating the import paths for `softwarecomposition` and `networkpolicy` in several files to point to the `v1beta1` version.
- Adjusting the test cases in `networkpolicy_test.go` and `generatednetworkpolicy_test.go` to reflect the updated import paths.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Move NP generate to v1beta1

README.md, pkg/registry/softwarecomposition/applicationprofile/strategy.go, pkg/registry/softwarecomposition/applicationprofile/strategy_test.go, pkg/registry/softwarecomposition/networkneighbors/strategy.go, pkg/registry/softwarecomposition/networkneighbors/strategy_test.go, pkg/utils/validations.go, pkg/utils/validations_test.go
___
enhancement, bug_fix
___
- Introduced validation and rejection logic for status updates in both ApplicationProfile and NetworkNeighbors to prevent invalid status transitions.
- Added utility functions in `pkg/utils/validations.go` for validating completion and status annotations with predefined valid values.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>strategy.go</strong><dd><code>Enhance ApplicationProfile Status Update Validation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/registry/softwarecomposition/applicationprofile/strategy.go
<li>Added validation and rejection logic for status updates in <br>ApplicationProfile.<br> …
=> status update checks

pkg/apis/softwarecomposition/types.go, pkg/apis/softwarecomposition/v1beta1/types.go, pkg/apis/softwarecomposition/v1beta1/zz_generated.conversion.go, pkg/apis/softwarecomposition/v1beta1/zz_generated.deepcopy.go, pkg/apis/softwarecomposition/zz_generated.deepcopy.go, pkg/cleanup/discovery.go, pkg/generated/openapi/zz_generated.openapi.go, pkg/registry/file/processor.go, pkg/registry/file/processor_test.go
enhancement
___
- Added support for ephemeral containers in `ApplicationProfileSpec`, including JSON tags, deep copy, conversion, and OpenAPI schema definitions.
- Updated discovery logic to include ephemeral containers in workload identification and image ID collection.
- Extended `ApplicationProfileProcessor` to process ephemeral containers, ensuring they are included in pre-save operations.
- Added unit tests to validate the processing of ephemeral containers.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td>
<details>
<summary><strong>types.go</strong><dd><code>Support for Ephemeral Containers in ApplicationProfileSpec</code></dd></summary>
<hr> …
=> support ephemeral containers

pkg/apis/softwarecomposition/syfttypes.go, pkg/apis/softwarecomposition/syfttypes_test.go, pkg/apis/softwarecomposition/v1beta1/syfttypes.go
___
bug_fix, tests
___
- Fixed an issue where `MetadataType` was not being set during the unpacking of `SyftPackage`.
- Added tests to ensure `SyftPackage` unmarshalling correctly sets `ID` and `MetadataType`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>syfttypes.go</strong><dd><code>Set MetadataType in SyftPackage Unpacking</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pkg/apis/softwarecomposition/syfttypes.go
- Explicitly …
=> Fix MetadataType in artifacts

pkg/apis/softwarecomposition/testdata/artifact.json
___
enhancement
___
- Added a new JSON artifact for the "adduser" package version 3.134 to the test data.
- This artifact includes detailed information such as package metadata, file lists with digests, license details, and more.
- Enhances the test data repository with a real-world example of package metadata for testing and development purposes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>artifact.json</strong><dd><code>Add Comprehensive JSON Artifact for "adduser" Package</code>&nbsp; &nbsp; &nbsp; &nbsp; …
=> adding artifact

pkg/apis/softwarecomposition/v1beta1/types.go, pkg/generated/openapi/zz_generated.openapi.go, pkg/registry/softwarecomposition/applicationprofile/strategy.go, pkg/registry/softwarecomposition/applicationprofile/strategy_test.go
___
enhancement, bug_fix
___
- Removed 'omitempty' from several fields in ApplicationProfileContainer to ensure they are always serialized.
- Updated OpenAPI schema to mark 'capabilities', 'execs', 'opens', 'syscalls' as required.
- Added logic to reject updates on ApplicationProfiles that are marked as complete and completed.
- Enhanced test coverage for update scenarios of ApplicationProfiles.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>types.go</strong><dd><code>Ensure Required Fields are Always Serialized</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> reject updates on complete app profile, remove omitempty

pkg/apis/softwarecomposition/v1beta1/spdx_types.go, pkg/apiserver/apiserver.go, pkg/registry/file/configurationscansummarystorage.go, pkg/registry/file/configurationscansummarystorage_test.go, pkg/registry/file/generatednetworkpolicy.go, pkg/registry/file/generatednetworkpolicy_test.go, pkg/registry/file/storage.go, pkg/registry/file/vulnerabilitysummarystorage.go, pkg/registry/file/vulnerabilitysummarystorage_test.go
refactor(file): Simplify storage object creation logic
In particular, this reduces the boilerplate of immutable storage layers (configscansummary, generated network policy and vulnerabilitysummary).
Also,
-  Simplify some list creation logic here and there.
-  Fix the issue that quotes were trimmed twice in some places in parsing side.
-  Don't pass pointers to interfaces (since interfaces are essentially typed pointers).
=> Minor non-functional refactoring/cleanup of storage layer

pkg/registry/file/watch.go, pkg/registry/file/watch_test.go
Fix the watch data race
Also, simplify the underlying logic to lure out what is actually going on here.
=> Fix watcher data race

pkg/cleanup/discovery.go
=> List only running pods

go.mod, go.sum, pkg/cleanup/cleanup.go, pkg/cleanup/cleanup_test.go, pkg/cleanup/discovery.go, pkg/registry/file/applicationprofile_processor.go, pkg/registry/file/networkneighborhood_processor.go, pkg/registry/file/processor.go, pkg/registry/file/storage.go, pkg/registry/file/storage_test.go
once released we can simplify https://github.com/kubescape/synchronizer/blame/f72c82a585f9c3469e9d48740efb2f97998a8724/tests/synchronizer_integration_test.go#L1323
=> increment resourceVersion on successful updates

main.go, pkg/cleanup/cleanup.go, pkg/cleanup/cleanup_test.go
it will help us spot AP and NN that were not marked as too big
=> warns if cleanup finds files bigger than 30MB

go.mod, go.sum, pkg/apis/softwarecomposition/networkpolicy/v2/networkpolicy_test.go, pkg/registry/file/applicationprofile_processor.go, pkg/registry/file/dynamicpathdetector/analyze_endpoints.go, pkg/registry/file/dynamicpathdetector/analyze_opens.go, pkg/registry/file/dynamicpathdetector/analyzer.go, pkg/registry/file/dynamicpathdetector/tests/analayze_opens_test.go, pkg/registry/file/dynamicpathdetector/tests/analyze_endpoints_test.go, pkg/registry/file/dynamicpathdetector/tests/analyze_opens_test.go, pkg/registry/file/dynamicpathdetector/tests/benchmark_test.go, pkg/registry/file/dynamicpathdetector/tests/coverage_test.go, pkg/registry/file/dynamicpathdetector/types.go, pkg/registry/file/dynamicpathdetector/utils.go, pkg/registry/file/networkneighborhood_processor.go, pkg/registry/file/processor.go, pkg/registry/softwarecomposition/applicationprofile/strategy_test.go, pkg/registry/softwarecomposition/networkneighborhood/strategy_test.go, pkg/registry/softwarecomposition/networkneighbors/strategy_test.go
=> Added dynamic open path detector

pkg/registry/file/applicationprofile_processor.go, pkg/registry/file/applicationprofile_processor_test.go, pkg/registry/file/processor.go
=> Added rule policy deflation

pkg/registry/file/storage.go, pkg/registry/file/storage_test.go, pkg/registry/file/vulnerabilitysummarystorage_test.go
while this aligns with regular api-server behavior, we should test all our components in case we don't expect Create() to fail
=> fail Create() if object already exists

pkg/cmd/server/start.go
This pull request includes changing the `pkg/cmd/server/start.go` file to disable authorization for the internal endpoint. Storage is only publishing an endpoint for the Kubernetes API Server (internal endpoint) and there is no point in verifying authorization when it is already done by this stage by the Kubernetes API Server.
* [`pkg/cmd/server/start.go`](diffhunk://#diff-100c9b6d0b2b9390b57a2ad09888fc069b32bf2f697b64ca9df6288f621da701R86-R88): Disabled authorization by setting `o.RecommendedOptions.Authorization` to `nil`, as the endpoint only answers the API server.
=> Disable authorization flow

pkg/cmd/server/start.go
This pull request corrects the way the TLS client CA file is handled in the server startup code. The most significant change is removing the file reading logic, which is replaced by directly setting the path from an environment variable.
Code simplification:
* [`pkg/cmd/server/start.go`](diffhunk://#diff-100c9b6d0b2b9390b57a2ad09888fc069b32bf2f697b64ca9df6288f621da701L90-R93): Removed the logic for reading the contents of the TLS client CA file and instead directly set the path from the `TLS_CLIENT_CA_FILE` environment variable.
=> Taking CA certificate from files directly

pkg/cmd/server/start.go
This pull request introduces a change to the `pkg/cmd/server/start.go` file to enhance server configuration by allowing the `SERVER_BIND_PORT` to be set via an environment variable. If the variable is not set or is invalid, the default port of 8443 is used.
Key change in server configuration:
* Added logic to check for the `SERVER_BIND_PORT` environment variable. If it exists and is a valid integer, the server bind port is set to the specified value. If not, a warning is logged, and the default port (8443) is used. (`[pkg/cmd/server/start.goR132-R144](diffhunk://#diff-100c9b6d0b2b9390b57a2ad09888fc069b32bf2f697b64ca9df6288f621da701R132-R144)`)
=> Making service port configurable

.gitignore, build/Dockerfile.debug, configuration/queue-configuration.json, go.mod, go.sum, pkg/cmd/server/start.go, pkg/config/config.go, pkg/config/config_test.go, pkg/queuemanager/manager.go, pkg/queuemanager/manager_test.go, pkg/statscollector/collector.go
This pull request introduces a queue management system for handling API requests with configurable queue lengths, worker counts, and maximum object sizes. It includes significant changes across multiple files to implement the new `QueueManager` and integrate it into the server configuration. The key changes are grouped below by theme:
* Added a new `QueueManager` in `pkg/queuemanager/manager.go` to manage per-kind request queues with configurable parameters like queue length, worker count, and maximum object size. It includes logic for request handling, queue creation, and throttling when queues are full.
* Updated `pkg/config/config.go` to include new configuration fields (`KindQueues`, `DefaultQueueLength`, `DefaultWorkerCount`, `DefaultMaxObjectSize`) and their corresponding default …
=> Implement queue management system with configurable parameters

pkg/registry/file/containerprofile_processor.go, tests/integration-test-suite/case_scale_deployment_partial_completion_test.go, tests/integration-test-suite/helm.go, tests/integration-test-suite/run-non-failover-tests.sh
This pull request introduces a new integration test for scaling deployments with partial completion behavior, improves logging for Helm commands, and updates the list of non-failover tests to include the new test. Below are the key changes grouped by theme:
- **New Test for Deployment Scaling**: Added `TestScaleDeploymentPartialCompletion` in `tests/integration-test-suite/case_scale_deployment_partial_completion_test.go`. This test validates the behavior of application profiles transitioning from partial to complete during deployment scaling and learning periods. It simulates scenarios such as node-agent downtime and scaling replicas.
- **Helm Command Logging**: Added a log statement in `EnsureKubescapeHelmRelease` to print the Helm command being executed for better traceability during …
=> Add integration test for deployment scaling with partial to complete

pkg/registry/file/networkneighborhood_storage.go
it was already in debug for AP
=> move "get cp object" message to debug in NN storage
